static_resources:
  listeners:
  - name: testing
    address: 
      socket_address:
        address: 127.0.0.1
        port_value: 10001
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          # access_log: 
          #   name: envoy.access_logger.stream
          #   typed_config:
          #     "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog

          use_remote_address: true
          # common_http_protocol_options:
          #   idle_timeout: 3600s # 1 hour
          #   headers_with_underscores_action: REJECT_REQUEST
          # http2_protocol_options:
          #   max_concurrent_streams: 100
          #   initial_stream_window_size: 65536 # 64 KiB
          #   initial_connection_window_size: 1048576 # 1 MiB
          # stream_idle_timeout: 300s
          # request_timeout: 300s
          route_config:
            virtual_hosts:
            - name: default
              domains: ["*"]
              routes:
              - match: 
                  prefix: "/"
                route:
                  cluster: httpbin
                  rate_limits:
                    - actions:
                      - request_headers:
                          descriptor_key: client_cert
                          header_name: forwarded-client-cert
          http_filters:
            - name: envoy.filters.http.ratelimit
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.http.ratelimit.v3.RateLimit
                domain: "collector"
                stage: 0
                failure_mode_deny: true
                request_type: external
                rate_limited_as_resource_exhausted: true
                rate_limit_service: 
                  grpc_service:
                    envoy_grpc:
                      cluster_name: ratelimit
                    timeout: 0.25s
                  transport_api_version: v3
            - name: envoy.filters.http.router

  - name: listener_0
    address: {socket_address: {address: 127.0.0.1, port_value: 10000}}
    listener_filters:
      - name: "envoy.filters.listener.tls_inspector"
        typed_config: {}
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          access_log: 
            name: envoy.access_logger.stream
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog

          forward_client_cert_details: APPEND_FORWARD
          set_current_client_cert_details:
            dns: true
          use_remote_address: true
          common_http_protocol_options:
            idle_timeout: 3600s # 1 hour
            headers_with_underscores_action: REJECT_REQUEST
          http2_protocol_options:
            max_concurrent_streams: 100
            initial_stream_window_size: 65536 # 64 KiB
            initial_connection_window_size: 1048576 # 1 MiB
          stream_idle_timeout: 300s
          request_timeout: 300s
          route_config:
            virtual_hosts:
            - name: default
              domains: ["*"]
              routes:
              - match: {prefix: "/scalagrpc"}
                route:
                  cluster: scalagrpc
                  rate_limits:
                    - actions:
                      - header_value_match:
                          descriptor_value: 'activities'
                          headers: 
                            - name: :path
                              prefix_match: "/scalagrpc"
          http_filters:
            - name: envoy.filters.http.grpc_json_transcoder
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.http.grpc_json_transcoder.v3.GrpcJsonTranscoder
                proto_descriptor: /etc/proto/activity.pb
                services: ["scalagrpc.Activities"]
                convert_grpc_status: true
                print_options:
                  add_whitespace: true
                  always_print_primitive_fields: true
                  always_print_enums_as_ints: false
                  preserve_proto_field_names: false
            - name: envoy.filters.http.ratelimit
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.http.ratelimit.v3.RateLimit
                domain: "collector"
                failure_mode_deny: true
                request_type: external
                rate_limited_as_resource_exhausted: true
                rate_limit_service: 
                  grpc_service:
                    envoy_grpc:
                      cluster_name: ratelimit
                    timeout: 0.25s
                  transport_api_version: v3
            - name: envoy.filters.http.router
      transport_socket:
        name: envoy.transport_sockets.tls
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
          require_client_certificate: true
          common_tls_context:
            tls_certificates:
            - certificate_chain: {filename: "/etc/certs/server.crt"}
              private_key: {filename: "/etc/certs/server.key"}
            validation_context:
              trusted_ca:
                filename: '/etc/certs/root-ca.crt'

  clusters:
  - name: scalagrpc
    type: LOGICAL_DNS
    connect_timeout: 0.2s
    lb_policy: ROUND_ROBIN
    dns_lookup_family: V4_ONLY
    load_assignment:
      cluster_name: scalagrpc
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: localhost
                port_value: 9000
    typed_extension_protocol_options:
      envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
        "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
        explicit_http_config:
          http2_protocol_options: {}
  - name: httpbin
    type: LOGICAL_DNS
    connect_timeout: 0.2s
    lb_policy: ROUND_ROBIN
    dns_lookup_family: V4_ONLY
    load_assignment:
      cluster_name: httpbin
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: localhost
                port_value: 9090
  - name: ratelimit
    type: LOGICAL_DNS
    lb_policy: ROUND_ROBIN
    dns_lookup_family: V4_ONLY
    connect_timeout: 0.5s
    http2_protocol_options: {}
    load_assignment:
      cluster_name: ratelimit
      endpoints:
        - lb_endpoints:
          - endpoint:
              address:
                socket_address:
                  address: localhost
                  port_value: 8081

